"""src/report.py — chart, table, markdown, artifacts. The palette.css
writer produces ready-to-paste `:root` variables (ported naming from
colorPallet: --color-bg-primary, --color-text-secondary, …)."""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone

from .colors import luminance
from .extract import CATEGORY_LABEL

CATEGORY_ORDER = ["background", "text", "border", "shadow", "svg"]
CSS_PREFIX = {"background": "bg", "text": "text", "border": "border",
              "shadow": "shadow", "svg": "icon"}


def _dark_light(hex_color: str) -> str:
    return "dark" if luminance(hex_color) < 0.5 else "light"


def build_chart_event(palette: dict) -> dict:
    """Bar chart: distinct color groups per category."""
    cats = [c for c in CATEGORY_ORDER if palette.get(c)] \
        or list(palette)
    return {
        "type": "chart",
        "chart_type": "bar",
        "title": "Color groups per category",
        "labels": [CATEGORY_LABEL.get(c, c) for c in cats],
        "series": [{"name": "color groups",
                    "values": [len(palette.get(c, [])) for c in cats]}],
    }


def build_table_event(palette: dict, top_n: int) -> dict:
    """The report table: every category's most-used colors in
    CATEGORY_ORDER, with hex, uses, variants, tone and role."""
    rows = []
    for category in CATEGORY_ORDER:
        for i, group in enumerate((palette.get(category) or [])[:top_n]):
            rows.append([
                group["representative"],
                CATEGORY_LABEL.get(category, category),
                group["count"],
                f"{len(group['variants'])} variant(s)"
                if len(group["variants"]) > 1 else "—",
                _dark_light(group["representative"]),
                "primary" if i == 0 else "",
            ])
    return {
        "type": "table",
        "columns": ["Color", "Category", "Uses", "Variants", "Tone", "Role"],
        "rows": rows,
    }


def build_markdown(url: str, palette: dict, total_found: int,
                   top_n: int) -> str:
    groups_total = sum(len(v) for v in palette.values())
    lines = [f"## 🎨 {groups_total} color group(s) from {total_found} "
             f"declaration(s)", "", f"`{url}`", ""]
    for category in CATEGORY_ORDER:
        groups = palette.get(category)
        if not groups:
            continue
        lines.append(f"### {CATEGORY_LABEL.get(category, category)}")
        lines.append("")
        for i, g in enumerate(groups[:top_n]):
            variants = ""
            if len(g["variants"]) > 1:
                others = ", ".join(v["color"] for v in g["variants"][1:5])
                variants = f" — also {others}" \
                    + ("…" if len(g["variants"]) > 5 else "")
            role = " (**primary**)" if i == 0 else \
                (" (secondary)" if i == 1 else "")
            lines.append(f"- `{g['representative']}` ×{g['count']}"
                         f"{role} · {_dark_light(g['representative'])}"
                         f"{variants}")
        if len(groups) > top_n:
            lines.append(f"- … {len(groups) - top_n} more group(s) "
                         f"(see palette.json)")
        lines.append("")
    lines.append("_`palette.css` has the ready-to-paste `:root` variables "
                 "(`--color-bg-primary` …); `palette.json` every group "
                 "with its variants. Feed a color to "
                 "[Favicon Generator](../favicon-generator) when you need "
                 "a matching icon set; check the page's overall health "
                 "with [Page SEO Audit](../page-seo-audit)._")
    lines.append("")
    return "\n".join(lines)


def build_palette_css(palette: dict) -> str:
    """The ready-to-paste variables block."""
    lines = [':root {',
             '  /* Generated by PyShell Color Palette '
             f'— {datetime.now(timezone.utc).strftime("%Y-%m-%d")} */', '']
    for category in CATEGORY_ORDER:
        groups = palette.get(category)
        if not groups:
            continue
        prefix = CSS_PREFIX.get(category, category)
        lines.append(f'  /* ── {CATEGORY_LABEL.get(category, category)} ── */')
        for i, g in enumerate(groups[:6]):
            suffix = 'primary' if i == 0 else \
                'secondary' if i == 1 else str(i + 1)
            lines.append(f'  --color-{prefix}-{suffix}: '
                         f'{g["representative"]};')
        lines.append('')
    lines.append('}')
    return '\n'.join(lines)


def write_artifacts(url: str, palette: dict, report: str) -> None:
    out_dir = os.environ.get("PYSHELL_OUTPUT_DIR")
    if not out_dir:
        return
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "palette.css"), "w",
              encoding="utf-8") as fh:
        fh.write(build_palette_css(palette) + "\n")
    with open(os.path.join(out_dir, "palette.json"), "w",
              encoding="utf-8") as fh:
        json.dump({
            "url": url,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "palette": palette,
        }, fh, indent=2, ensure_ascii=False)
    with open(os.path.join(out_dir, "report.md"), "w",
              encoding="utf-8") as fh:
        fh.write(report + "\n")
