"""Emit sprite.php — the WordPress include.

The sprite defs, identical to ``sprite.svg``, written as a PHP file meant to
be ``include``d once where the defs are needed (e.g. a theme footer). There is
no ``<?xml`` declaration (we never emit one), so the SVG content is safe
inside a PHP file: a leading one-line ``<?php /* … */ ?>`` documents that the
file is generated, and everything after it is output verbatim when included.
"""
from __future__ import annotations

from .emit_sprite import write_artifact

_HEADER = "<?php /* SVG sprite — generated by svg-sprite-build. Do not edit. */ ?>\n"


def emit_wordpress(sprite_svg: str, out_dir: str) -> str:
    return write_artifact(out_dir, "sprite.php", _HEADER + sprite_svg)
