"""B7 — write migration.css, the killer artifact.

The old markup ``<i class="fa fa-user"></i>`` is scattered across a theme nobody
wants to touch. This stylesheet maps each legacy class to a ``mask-image``
clipped from the sprite fragment, so the existing markup keeps working with the
font file deleted. Not as clean as real ``<use>`` markup, but it is the
difference between a five-minute migration and a two-day one.

Each rule also neutralizes the icon's ``::before { content }`` (which would
otherwise render a missing-glyph box once the font is gone) and paints the
glyph with ``currentColor`` so it inherits text color exactly as the font did.
"""
from __future__ import annotations

# The fragment mask works because modern browsers render a <symbol> referenced
# by id when an SVG is loaded as an external image (background/mask url()).
# For browsers without external-fragment mask support, switch to <use> markup.
from .util import atomic_write_text


def emit_shim(
    out_path: str,
    class_to_sprite: dict[str, str],
    sprite_filename: str = "sprite.svg",
) -> str:
    """Render migration.css for every legacy class → sprite id mapping."""
    lines: list[str] = [
        "/* migration.css — generated by svg-sprite-from-font.",
        " *",
        " * Keeps legacy <i class=\"fa fa-user\"></i> markup working after the",
        " * icon font is deleted. Load this AFTER the theme's icon-font CSS so",
        " * the !important content override wins. Each glyph is painted via a",
        " * mask clipped from the sprite, with currentColor for inheritance.",
        " */",
        "",
    ]
    for cls in sorted(class_to_sprite):
        sid = class_to_sprite[cls]
        url = f'url("{sprite_filename}#{sid}")'
        lines.append(f".{cls}::before {{ content: none !important; }}")
        lines.append(f".{cls} {{")
        lines.append("  display: inline-block;")
        lines.append("  width: 1em;")
        lines.append("  height: 1em;")
        lines.append("  vertical-align: -.125em;")
        lines.append("  background-color: currentColor;")
        lines.append(f"  -webkit-mask-image: {url};")
        lines.append(f"          mask-image: {url};")
        lines.append("  -webkit-mask-repeat: no-repeat;")
        lines.append("          mask-repeat: no-repeat;")
        lines.append("  -webkit-mask-size: contain;")
        lines.append("          mask-size: contain;")
        lines.append("}")
        lines.append("")
    atomic_write_text(out_path, "\n".join(lines))
    return out_path
