"""B7 — write sprite.php, the WordPress include.

Hooks ``wp_body_open`` (with a ``wp_footer`` fallback for themes missing the
hook) to print the inline sprite exactly once, and provides
``mn_icon( $name, $class = '', $label = '' )`` which renders an accessible
``<use>``: ``aria-hidden`` when no label is given, ``role="img"`` + ``<title>``
when one is.
"""
from __future__ import annotations

from jinja2 import Environment

from .util import atomic_write_text

_PHP_TEMPLATE = """<?php
/**
 * SVG icon sprite — generated by svg-sprite-from-font.
 *
 * Include once from functions.php:
 *   require_once get_template_directory() . '/sprite.php';
 *
 * The sprite prints once at `wp_body_open` (wp_footer fallback for themes
 * without the hook), then render icons with mn_icon():
 *   mn_icon( 'user' );                            // decorative
 *   mn_icon( 'user', 'btn-icon', 'Log out' );     // labelled (role="img")
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }

if ( ! defined( 'MN_ICON_PREFIX' ) ) {
\tdefine( 'MN_ICON_PREFIX', {{ prefix|tojson }} );
}

add_action( 'wp_body_open', 'mn_print_sprite', 1 );
add_action( 'wp_footer', 'mn_print_sprite', 100 );

function mn_print_sprite() {
\tstatic $printed = false;
\tif ( $printed ) { return; }
\t$printed = true;
\techo "<style>.mn-icon{display:inline-block;width:1em;height:1em;fill:currentColor;vertical-align:-.125em}</style>\\n";
\techo <<<'MN_SPRITE'
{{ sprite_body }}
MN_SPRITE;
}

function mn_icon( $name, $class = '', $label = '' ) {
\t$id    = MN_ICON_PREFIX . $name;
\t$extra = $class !== '' ? ' ' . esc_attr( $class ) : '';
\tif ( $label !== '' ) {
\t\tprintf(
\t\t\t'<svg role="img" aria-label="%1$s" class="mn-icon%2$s"><title>%1$s</title><use href="%3$s"></use></svg>',
\t\t\tesc_attr( $label ),
\t\t\t$extra,
\t\t\tesc_attr( '#' . $id )
\t\t);
\t} else {
\t\tprintf(
\t\t\t'<svg aria-hidden="true" focusable="false" class="mn-icon%1$s"><use href="%2$s"></use></svg>',
\t\t\t$extra,
\t\t\tesc_attr( '#' . $id )
\t\t);
\t}
}
"""


def emit_wordpress(out_path: str, sprite_body: str, sprite_prefix: str) -> str:
    """Render sprite.php with the inline sprite and write it atomically."""
    env = Environment(autoescape=False, keep_trailing_newline=True)
    env.filters["tojson"] = lambda v: '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'
    tpl = env.from_string(_PHP_TEMPLATE)
    php = tpl.render(sprite_body=sprite_body.rstrip("\n"), prefix=sprite_prefix)
    atomic_write_text(out_path, php)
    return out_path
