"""src/report.py — the markdown report, the results table, the fail2ban
jail snippet, and the JSON artifact."""
from __future__ import annotations

import json
import os
from collections import Counter

from .analysis import Analyzer, IPProfile, Kind


def _fmt_ts(ts) -> str:
    return ts.strftime("%Y-%m-%d %H:%M") if ts else "—"


def _geo_suffix(ip: str, geo: dict[str, dict]) -> str:
    entry = geo.get(ip)
    if not entry:
        return ""
    bits = [entry.get("country") or "?"]
    if entry.get("proxy"):
        bits.append("proxy/VPN")
    if entry.get("hosting"):
        bits.append("hosting")
    return " · " + " · ".join(bits)


def _method_label(event) -> str:
    return event.method or "—"


def build_table_event(analyzer: Analyzer, geo: dict[str, dict],
                      top_n: int) -> dict:
    """The Results-tab summary: one row per brute-force IP, the worst
    (most failures, most wins) first."""
    rows = []
    for profile in analyzer.bruteforce_ips()[:top_n]:
        wins = len(profile.accepted)
        rows.append([
            profile.ip,
            profile.failures,
            len(profile.users_tried),
            "🔴 YES" if wins else "no",
            _fmt_ts(profile.last_seen),
            (geo.get(profile.ip, {}).get("country") or "—"),
        ])
    return {
        "type": "table",
        "columns": ["IP", "Failed attempts", "Users tried",
                    "Got in?", "Last seen", "Country"],
        "rows": rows,
    }


def build_fail2ban_conf(analyzer: Analyzer, top_n: int) -> str:
    """A ready-to-paste /etc/fail2ban/jail.local for the sshd jail, with
    the observed offenders listed as a comment block and manual ufw
    deny lines for the top IPs (for the no-fail2ban case)."""
    flagged = analyzer.bruteforce_ips()
    lines = [
        "# /etc/fail2ban/jail.local — generated by PyShell SSH Log Check",
        "# from the analyzed logs' worst offenders.",
        "",
        "[sshd]",
        "enabled  = true",
        f"maxretry = {max(3, min(analyzer.bruteforce_threshold, 10))}",
        "findtime = 10m",
        "bantime  = 1h",
        "backend  = systemd   # drop this line on non-systemd servers",
        "",
    ]
    if flagged:
        lines.append("# Worst offenders observed in the analyzed logs:")
        for profile in flagged[:top_n]:
            note = ("; ALSO ACCEPTED A LOGIN" if profile.accepted
                    else "")
            lines.append(f"#   {profile.ip} — {profile.failures} failed "
                         f"attempt(s){note}")
        lines.append("")
        lines.append("# Manual block, no fail2ban needed (ufw):")
        for profile in flagged[:top_n]:
            if not profile.accepted:  # never block an IP that also logged in
                lines.append(f"# ufw deny from {profile.ip} to any port 22")
    lines.append("")
    return "\n".join(lines)


def build_markdown(analyzer: Analyzer, geo: dict[str, dict],
                   top_n: int) -> str:
    flagged = analyzer.bruteforce_ips()
    wins = analyzer.compromised_candidates()
    accepted = analyzer.accepted_events
    lo, hi = analyzer.period

    if wins:
        head = f"## 🔴 {len(wins)} IP(s) failed *and then got in*"
    elif flagged:
        head = f"## 🟠 {len(flagged)} brute-force IP(s), no breakthrough"
    elif accepted:
        head = "## 🟢 No brute force detected"
    else:
        head = "## ⚪ No auth events with IPs detected"
    lines = [head, ""]

    lines.append(f"- Events parsed: **{analyzer.events:,}** · "
                 f"accepted logins: **{len(accepted)}** · "
                 f"preauth probe noise: {analyzer.preauth_noise:,}")
    if lo and hi:
        lines.append(f"- Period: {_fmt_ts(lo)} → {_fmt_ts(hi)}")
    lines.append("")

    # -- the critical chains ------------------------------------------------
    if wins:
        lines += ["### 🔴 Brute force that may have won", "",
                  "Failures from one IP followed by an accepted login — "
                  "treat these accounts as compromised until proven "
                  "otherwise (rotate keys/passwords, check sessions):",
                  ""]
        for p in wins[:top_n]:
            first = p.accepted[0]
            lines.append(f"- **{p.ip}** — {p.failures} failure(s), then "
                         f"`{first.user}` logged in via "
                         f"{_method_label(first)} at "
                         f"{_fmt_ts(first.ts)}"
                         + _geo_suffix(p.ip, geo))
        lines.append("")

    # -- brute-force table ----------------------------------------------------
    if flagged:
        lines += [f"### Brute-force IPs (≥{analyzer.bruteforce_threshold} "
                  f"failed attempts)", "",
                  "| IP | Failed | Users tried | Got in | Last seen | Geo |",
                  "| --- | --- | --- | --- | --- | --- |"]
        for p in flagged[:top_n]:
            got_in = f"🔴 {len(p.accepted)}×" if p.accepted else "—"
            lines.append(f"| {p.ip} | {p.failures} | "
                         f"{len(p.users_tried)} | {got_in} | "
                         f"{_fmt_ts(p.last_seen)} | "
                         f"{(geo.get(p.ip, {}).get('country') or '—')}"
                         f"{' · proxy' if geo.get(p.ip, {}).get('proxy') else ''}"
                         f"{' · hosting' if geo.get(p.ip, {}).get('hosting') else ''} |")
        lines += ["",
                  f"_{len(flagged)} IP(s) at or over the threshold; the "
                  f"table shows the top {min(top_n, len(flagged))}, "
                  f"`findings.json` has them all._", ""]

    # -- tried usernames ----------------------------------------------------------
    usernames = analyzer.tried_usernames(top_n)
    if usernames:
        top_users = ", ".join(f"`{u}` ({n})" for u, n in usernames[:10])
        lines += ["### Usernames the attackers tried", "",
                  f"{top_users}", ""]
        lines.append("_`invalid user` probes mean the account doesn't "
                     "exist — disable password auth entirely and these "
                     "become pure noise._")
        lines.append("")

    # -- accepted logins --------------------------------------------------------------
    if accepted:
        lines += ["### Accepted logins", "",
                  "| Time | User | IP | Method | Geo |",
                  "| --- | --- | --- | --- | --- |"]
        for e in accepted[:top_n]:
            lines.append(f"| {_fmt_ts(e.ts)} | {e.user} | {e.ip} | "
                         f"{_method_label(e)} | "
                         f"{(geo.get(e.ip, {}).get('country') or '—')} |")
        if len(accepted) > top_n:
            lines.append(f"| … | +{len(accepted) - top_n} more | | | |")
        lines.append("")

    # -- advice ---------------------------------------------------------------------------
    lines += ["### Next steps", ""]
    if wins:
        lines.append("1. **Rotate credentials now** for every account in "
                     "the red section — keys and passwords.")
        lines.append("2. Review sessions and `~/.ssh/authorized_keys` on "
                     "those accounts.")
    lines.append(("3. " if wins else "1. ")
                 + "Install the generated **fail2ban jail** "
                   "(`fail2ban_jail.conf` artifact) or paste the ufw "
                   "deny lines from it.")
    lines.append(("4. " if wins else "2. ")
                 + "Disable password authentication if it's still on — "
                   "keys only is the structural fix.")
    lines.append(("5. " if wins else "3. ")
                 + "Cross-check the web side with "
                   "[Log Attack Checker](../log-attack-checker): the same "
                   "IPs often run both fronts.")
    lines.append("")

    if not geo and any(p.failures for p in analyzer.ips.values()):
        lines.append("_Geo enrichment unavailable (offline or "
                     "skipped) — country columns show —._")
        lines.append("")

    lo_txt = _fmt_ts(lo) if lo else "n/a"
    hi_txt = _fmt_ts(hi) if hi else "n/a"
    lines.append(f"_Reads logs only; nothing was sent anywhere except the "
                 f"optional ip-api.com lookup of attacker IPs. Period "
                 f"{lo_txt} → {hi_txt}._")
    lines.append("")
    return "\n".join(lines)


def write_artifacts(analyzer: Analyzer, geo: dict[str, dict],
                    report: str, fail2ban: str) -> None:
    out_dir = os.environ.get("PYSHELL_OUTPUT_DIR")
    if not out_dir:
        return
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "report.md"), "w",
              encoding="utf-8") as fh:
        fh.write(report + "\n")

    payload = {
        "events": analyzer.events,
        "period": [analyzer.period[0].isoformat()
                   if analyzer.period[0] else None,
                   analyzer.period[1].isoformat()
                   if analyzer.period[1] else None],
        "bruteforce_threshold": analyzer.bruteforce_threshold,
        "whitelist": sorted(analyzer.whitelist),
        "bruteforce_ips": [
            {"ip": p.ip, "failures": p.failures,
             "users_tried": dict(p.users_tried.most_common()),
             "accepted": [{"user": e.user, "method": e.method,
                           "ts": e.ts.isoformat() if e.ts else None}
                          for e in p.accepted],
             "first_seen": p.first_seen.isoformat()
             if p.first_seen else None,
             "last_seen": p.last_seen.isoformat() if p.last_seen else None,
             "geo": geo.get(p.ip)}
            for p in analyzer.bruteforce_ips()
        ],
        "compromised_candidates": [p.ip for p in
                                   analyzer.compromised_candidates()],
        "accepted_logins": [
            {"user": e.user, "ip": e.ip, "method": e.method,
             "ts": e.ts.isoformat() if e.ts else None,
             "geo": geo.get(e.ip)}
            for e in analyzer.accepted_events
        ],
    }
    with open(os.path.join(out_dir, "findings.json"), "w",
              encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)

    with open(os.path.join(out_dir, "fail2ban_jail.conf"), "w",
              encoding="utf-8") as fh:
        fh.write(fail2ban)
